#
# Import new image on base image update
#
name: ACR base image import
trigger: none
pr: none
variables:
  environment: 'nonprod'
  acrName: hmctspublic
  baseImage: library/node
  baseRegistry: docker.io
  baseTag: 8-alpine
  baseImageType: docker  # docker or gcr
  targetImage: hmcts/base/node/alpine-lts-8
  targetTag: 8-alpine
steps:
- task: AzureCLI@1
  displayName: 'Get digest for repository/tag from base registry'
  inputs:
    azureSubscription: azurerm-nonprod
    scriptLocation: 'inlineScript'
    inlineScript: |
      if [ $(baseImageType) == "docker" ]
      then
        # docker registry
        _token=$(curl --silent "https://auth.docker.io/token?scope=repository:$(baseImage):pull&service=registry.docker.io" | jq -r '.token')
        _digest=$(curl --silent --header "Accept: application/vnd.docker.distribution.manifest.v2+json" --header "Authorization: Bearer $_token" \
        "https://registry-1.docker.io/v2/$(baseImage)/manifests/$(baseTag)" | jq -r '.config.digest')
      else
        # google registry (gcr)
        _digest=$(curl --silent "https://gcr.io/v2/$(baseImage)/manifests/$(baseTag)" |jq -r '.config.digest')
      fi
      [ "$_digest" == "" ] && echo "Error: cannot get image digest for $(baseImage):$(baseTag)" && exit 1
      echo "Base registry current digest for $(baseImage):$(baseTag): $_digest"
      _acr_digest=$(az acr repository show-manifests -n $(acrName) --repository $(baseImage) --query '[].[digest,tags[?@ == `8-alpine`]]|[0]|[0]' > /dev/null 2>&1)
      echo "Target registry current digest for $(baseImage):$(baseTag): $_acr_digest"
      if [[ "$_acr_digest" == "" || "$_acr_digest" != "$_digest" ]]
      then
        echo "Importing $_acr_digest ..."
        az acr import --name $(acrName) --source $(baseRegistry)/$(baseImage):$(baseTag) --image $(targetImage):$(targetTag)-${_digest:7:6} 
      fi
