#
# Import new image on base image update
#
name: ACR base image import
trigger: none
pr: none
variables:
  environment: 'nonprod'
  acrName: hmctspublic
  baseImage: library/node
  baseRegistry: docker.io
  baseTag: 8-alpine
  baseImageType: docker  # docker or gcr
  targetRegistry: hmctspublic.azurecr.io
  targetImage: hmcts/base/node/alpine-lts-8

steps:
- task: AzureCLI@1
  displayName: 'Import from base registry if new digest available for tag'
  inputs:
    azureSubscription: azurerm-nonprod
    scriptLocation: 'inlineScript'
    inlineScript: |
      if [ $(baseImageType) == "docker" ]
      then
        # docker registry
        _token=$(curl --silent "https://auth.docker.io/token?scope=repository:$(baseImage):pull&service=registry.docker.io" | jq -r '.token')
        _digest=$(curl --silent --header "Accept: application/vnd.docker.distribution.manifest.v2+json" --header "Authorization: Bearer $_token" \
        "https://registry-1.docker.io/v2/$(baseImage)/manifests/$(baseTag)" | jq -r '.config.digest')
      else
        # google registry (gcr)
        _digest=$(curl --silent "https://gcr.io/v2/$(baseImage)/manifests/$(baseTag)" |jq -r '.config.digest')
      fi
      [ "$_digest" == "" ] && echo "Error: cannot get image digest for $(baseImage):$(baseTag)" && exit 1
      echo "Base registry current digest for $(baseImage):$(baseTag): $_digest"
      _acr_digest=$(az acr repository show-manifests -n $(acrName) --repository $(targetImage) --query '[].[digest,tags[?@ == `$(baseTag)`]]|[0]|[0]' > /dev/null 2>&1)
      echo "Target registry current digest for $(baseImage):$(baseTag): $_acr_digest"
      [[ "$_acr_digest" != "" && "$_acr_digest" == "$_digest" ]] && exit 2  # Nothing else to do
      echo "Importing $_acr_digest ..."
      az acr import --name $(acrName) --source $(baseRegistry)/$(baseImage):$(baseTag) --image $(targetImage):$(baseTag)-${_digest:7:6} 

- task: AzureCLI@1
  displayName: 'Security scan new image'
  inputs:
    azureSubscription: azurerm-nonprod
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "This is a placeholder for NeuVector image scan"

- task: AzureCLI@1
  displayName: 'Re-tag new image using the base tag'
  inputs:
    azureSubscription: azurerm-nonprod
    scriptLocation: 'inlineScript'
    inlineScript: |
      _acr_digest=$(az acr repository show-manifests -n $(acrName) --repository $(targetImage) --query '[].[digest,tags[?@ == `$(baseTag)`]]|[0]|[0]' > /dev/null 2>&1)
      [ "$_acr_digest" != "" ] && az acr repository untag -n $(acrName) --image $(targetImage):$(baseTag)
      az acr import --name $(acrName) --source $(targetRegistry)/$(targetImage):$(baseTag)-${_digest:7:6} --image $(targetImage):$(baseTag) 
