#
## Scan and import container images using Trivy
## This pipeline scans container images for vulnerabilities before importing to ACR
##
name: Trivy Scan and ACR Import

trigger:
  - master
pr: none
schedules:
- cron: '0 1 * * *'
  displayName: Daily vulnerability scan and import
  branches:
    include:
    - master
  always: 'true'

# Define images to scan as a parameter (allows modification at queue time)
parameters:
- name: imagesToScan
  type: object
  displayName: 'Images to scan and import'
  default:
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java25-debian13'
    baseTag: 'latest'
    targetImage: 'imported/distroless/java25'
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java25-debian13'
    baseTag: 'debug'
    targetImage: 'imported/distroless/java25'
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java21-debian12'
    baseTag: 'latest'
    targetImage: 'imported/distroless/java21'
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java21-debian12'
    baseTag: 'debug'
    targetImage: 'imported/distroless/java21'
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java17-debian12'
    baseTag: 'latest'
    targetImage: 'imported/distroless/java17'
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java17-debian12'
    baseTag: 'debug'
    targetImage: 'imported/distroless/java17'

variables:
  acrName: hmctspublic
  targetRegistry: hmctspublic.azurecr.io
  keyvaultName: 'infra-vault-prod'
  serviceConnection: 'DCD-CNP-PROD'
  # Trivy configuration
  trivyVersion: '0.68.1'  # Latest stable release with improved vulnerability detection
  severityThreshold: 'CRITICAL,HIGH'
  trivyTimeout: '10m'

stages:
- stage: ScanAndImport
  displayName: 'Scan with Trivy and Import to ACR'
  jobs:
  - job: ScanAndImportImages
    displayName: 'Scan with Trivy and Import to ACR'
    timeoutInMinutes: 120  # 2 hours max - prevents hanging
    pool:
      name: hmcts-cftptl-agent-pool

    steps:
    # Get secrets from Key Vault for ACR authentication and notifications
    - task: AzureKeyVault@2
      displayName: 'Get ACR credentials from Key Vault'
      inputs:
        azureSubscription: $(serviceConnection)
        keyVaultName: $(keyvaultName)
        secretsFilter: 'registry-public-username,registry-public-password,registry-slack-webhook'

    # Setup Trivy scanner (install binary and update databases)
    - template: templates/setup-trivy.yml
      parameters:
        trivyVersion: $(trivyVersion)

    # Loop over each image using Azure DevOps native each loops
    - ${{ each image in parameters.imagesToScan }}:
      # Check if new version exists
      - task: AzureCLI@2
        displayName: 'Check version: ${{ image.baseImage }}:${{ image.baseTag }}'
        name: check_${{ replace(replace(image.baseImage, '/', '_'), '-', '_') }}_${{ replace(image.baseTag, '-', '_') }}
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: scriptPath
          scriptPath: check-base-tag.sh
          arguments: >
            --baseImage "${{ image.baseImage }}"
            --baseRegistry "${{ image.baseRegistry }}"
            --baseTag "${{ image.baseTag }}"
            --targetImage "${{ image.targetImage }}"
            --acrName "$(acrName)"

      # Scan image with Trivy (only if new version found)
      - template: templates/scan-image.yml
        parameters:
          baseRegistry: ${{ image.baseRegistry }}
          baseImage: ${{ image.baseImage }}
          baseTag: ${{ image.baseTag }}
          severityThreshold: $(severityThreshold)
          trivyTimeout: $(trivyTimeout)
          taskNameSuffix: ${{ replace(replace(image.baseImage, '/', '_'), '-', '_') }}_${{ replace(image.baseTag, '-', '_') }}
          condition: eq(variables['check_${{ replace(replace(image.baseImage, '/', '_'), '-', '_') }}_${{ replace(image.baseTag, '-', '_') }}.newTagFound'], 'true')

      # Import to ACR (only if scan passed)
      - template: templates/import-image.yml
        parameters:
          baseRegistry: ${{ image.baseRegistry }}
          baseImage: ${{ image.baseImage }}
          baseTag: ${{ image.baseTag }}
          targetImage: ${{ image.targetImage }}
          acrName: $(acrName)
          serviceConnection: $(serviceConnection)
          baseDigest: $(check_${{ replace(replace(image.baseImage, '/', '_'), '-', '_') }}_${{ replace(image.baseTag, '-', '_') }}.baseDigest)
          taskNameSuffix: ${{ replace(replace(image.baseImage, '/', '_'), '-', '_') }}_${{ replace(image.baseTag, '-', '_') }}
          condition: and(eq(variables['check_${{ replace(replace(image.baseImage, '/', '_'), '-', '_') }}_${{ replace(image.baseTag, '-', '_') }}.newTagFound'], 'true'), eq(variables['scan_${{ replace(replace(image.baseImage, '/', '_'), '-', '_') }}_${{ replace(image.baseTag, '-', '_') }}.scanPassed'], 'true'))

      # # Re-tag image
      # - task: AzureCLI@2
      #   displayName: 'Tag: ${{ image.baseImage }}:${{ image.baseTag }}'
      #   condition: |
      #     and(
      #       eq(variables['check_${{ replace(replace(image.baseImage, '/', '_'), '-', '_') }}_${{ replace(image.baseTag, '-', '_') }}.newTagFound'], 'true'),
      #       eq(variables['scan_${{ replace(replace(image.baseImage, '/', '_'), '-', '_') }}_${{ replace(image.baseTag, '-', '_') }}.scanPassed'], 'true')
      #     )
      #   inputs:
      #     azureSubscription: $(serviceConnection)
      #     scriptType: bash
      #     scriptLocation: scriptPath
      #     scriptPath: tag-new-image.sh
      #     arguments: >
      #       --baseTag "${{ image.baseTag }}"
      #       --targetImage "${{ image.targetImage }}"
      #       --acrName "$(acrName)"
      #       --targetRegistry "$(targetRegistry)"
      #       --baseDigest "$(check_${{ replace(replace(image.baseImage, '/', '_'), '-', '_') }}_${{ replace(image.baseTag, '-', '_') }}.baseDigest)"
      #       --acrDigest "$(check_${{ replace(replace(image.baseImage, '/', '_'), '-', '_') }}_${{ replace(image.baseTag, '-', '_') }}.acrDigest)"

- stage: CreateCache
  displayName: 'Create ACR Cache'
  dependsOn: ScanAndImport
  condition: succeeded()
  jobs:
  - job: CreateACRCache
    displayName: 'Create ACR Cache'
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: AzureCLI@2
        displayName: 'Create ACR Cache'
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: scriptPath
          scriptPath: acr-cache.sh
