#
## Main Orchestration Pipeline
## Scan and import container images using Trivy
## This pipeline coordinates base image imports and ACR cache rule creation
##
name: Trivy Scan and ACR Import

trigger:
  - master
pr: none
schedules:
- cron: '0 1 * * *'
  displayName: Daily vulnerability scan and import
  branches:
    include:
    - master
  always: 'true'

# Parameters with inline defaults
parameters:
- name: baseImagestoImport
  type: object
  displayName: 'Images to scan and import'
  default:
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java25-debian13'
    baseTag: 'latest'
    targetImage: 'imported/distroless/java25'
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java25-debian13'
    baseTag: 'debug'
    targetImage: 'imported/distroless/java25'
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java21-debian12'
    baseTag: 'latest'
    targetImage: 'imported/distroless/java21'
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java21-debian12'
    baseTag: 'debug'
    targetImage: 'imported/distroless/java21'
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java17-debian12'
    baseTag: 'latest'
    targetImage: 'imported/distroless/java17'
  - baseRegistry: 'gcr.io'
    baseImage: 'distroless/java17-debian12'
    baseTag: 'debug'
    targetImage: 'imported/distroless/java17'

- name: cacheRulesToValidate
  type: object
  displayName: 'Cache rules to create and validate'
  default:
  - ruleName: 'postgresql'
    baseRegistry: 'docker.io'
    baseImage: 'bitnami/postgresql'
    destinationRepo: 'imported/bitnami/postgresql'
  - ruleName: 'postgres-exporter'
    baseRegistry: 'docker.io'
    baseImage: 'bitnami/postgres-exporter'
    destinationRepo: 'imported/postgres-exporter'
  - ruleName: 'postgres'
    baseRegistry: 'docker.io'
    baseImage: 'library/postgres'
    destinationRepo: 'imported/postgres'
  - ruleName: 'postgresql-client'
    baseRegistry: 'docker.io'
    baseImage: 'jbergknoff/postgresql-client'
    destinationRepo: 'imported/jbergknoff/postgresql-client'
  - ruleName: 'curl-cache'
    baseRegistry: 'docker.io'
    baseImage: 'curlimages/curl'
    destinationRepo: 'imported/curlimages/curl'
  - ruleName: 'elastic-search'
    baseRegistry: 'docker.io'
    baseImage: 'elasticsearch/elasticsearch'
    destinationRepo: 'imported/elastic/elasticsearch'
  - ruleName: 'external-dns'
    baseRegistry: 'docker.io'
    baseImage: 'bitnami/external-dns'
    destinationRepo: 'imported/bitnami/external-dns'
  - ruleName: 'kubectl'
    baseRegistry: 'docker.io'
    baseImage: 'bitnami/kubectl'
    destinationRepo: 'imported/bitnami/kubectl'
  - ruleName: 'bitnami-redis'
    baseRegistry: 'docker.io'
    baseImage: 'bitnami/redis'
    destinationRepo: 'imported/bitnami/redis'
  - ruleName: 'bitnami-redis-exporter'
    baseRegistry: 'docker.io'
    baseImage: 'bitnami/redis-exporter'
    destinationRepo: 'imported/bitnami/redis-exporter'
  - ruleName: 'bitnami-redis-sentinel'
    baseRegistry: 'docker.io'
    baseImage: 'bitnami/redis-sentinel'
    destinationRepo: 'imported/bitnami/redis-sentinel'
  - ruleName: 'pact-broker'
    baseRegistry: 'docker.io'
    baseImage: 'dius/pact-broker'
    destinationRepo: 'imported/dius/pact-broker'
  - ruleName: 'datawire-tel2'
    baseRegistry: 'docker.io'
    baseImage: 'datawire/tel2'
    destinationRepo: 'imported/datawire/tel2'
  - ruleName: 'service-catalog'
    baseRegistry: 'docker.io'
    baseImage: 'drycc/service-catalog'
    destinationRepo: 'imported/drycc/service-catalog'
  - ruleName: 'dynatrace-operator'
    baseRegistry: 'docker.io'
    baseImage: 'dynatrace/dynatrace-operator'
    destinationRepo: 'imported/dynatrace/dynatrace-operator'
  - ruleName: 'fluent-bit'
    baseRegistry: 'docker.io'
    baseImage: 'fluent/fluent-bit'
    destinationRepo: 'imported/fluent/fluent-bit'
  - ruleName: 'grafana'
    baseRegistry: 'docker.io'
    baseImage: 'grafana/grafana'
    destinationRepo: 'imported/grafana'
  - ruleName: 'testkube-api-server'
    baseRegistry: 'docker.io'
    baseImage: 'kubeshop/testkube-api-server'
    destinationRepo: 'imported/kubeshop/testkube-api-server'
  - ruleName: 'testkube-dashboard'
    baseRegistry: 'docker.io'
    baseImage: 'kubeshop/testkube-dashboard'
    destinationRepo: 'imported/kubeshop/testkube-dashboard'
  - ruleName: 'testkube-operator'
    baseRegistry: 'docker.io'
    baseImage: 'kubeshop/testkube-operator'
    destinationRepo: 'imported/kubeshop/testkube-operator'
  - ruleName: 'minio'
    baseRegistry: 'docker.io'
    baseImage: 'minio/minio'
    destinationRepo: 'imported/minio/minio'
  - ruleName: 'neuvector-controller'
    baseRegistry: 'docker.io'
    baseImage: 'neuvector/controller'
    destinationRepo: 'imported/neuvector/controller'
  - ruleName: 'neuvector-enforcer'
    baseRegistry: 'docker.io'
    baseImage: 'neuvector/enforcer'
    destinationRepo: 'imported/neuvector/enforcer'
  - ruleName: 'neuvector-manager'
    baseRegistry: 'docker.io'
    baseImage: 'neuvector/manager'
    destinationRepo: 'imported/neuvector/manager'
  - ruleName: 'neuvector-scanner'
    baseRegistry: 'docker.io'
    baseImage: 'neuvector/scanner'
    destinationRepo: 'imported/neuvector/scanner'
  - ruleName: 'neuvector-updater'
    baseRegistry: 'docker.io'
    baseImage: 'neuvector/updater'
    destinationRepo: 'imported/neuvector/updater'
  - ruleName: 'traefik'
    baseRegistry: 'docker.io'
    baseImage: 'library/traefik'
    destinationRepo: 'imported/traefik'
  - ruleName: 'configmap-reload'
    baseRegistry: 'docker.io'
    baseImage: 'jimmidyson/configmap-reload'
    destinationRepo: 'imported/jimmidyson/configmap-reload'
  - ruleName: 'k8s-sidecar'
    baseRegistry: 'docker.io'
    baseImage: 'kiwigrid/k8s-sidecar'
    destinationRepo: 'imported/kiwigrid/k8s-sidecar'
  - ruleName: 'openssh-server'
    baseRegistry: 'docker.io'
    baseImage: 'linuxserver/openssh-server'
    destinationRepo: 'imported/linuxserver/openssh-server'
  - ruleName: 'mailhog'
    baseRegistry: 'docker.io'
    baseImage: 'mailhog/mailhog'
    destinationRepo: 'imported/mailhog/mailhog'
  - ruleName: 'nats-rule'
    baseRegistry: 'docker.io'
    baseImage: 'library/nats'
    destinationRepo: 'imported/nats'
  - ruleName: 'nats-server-config-reloader'
    baseRegistry: 'docker.io'
    baseImage: 'natsio/nats-server-config-reloader'
    destinationRepo: 'imported/natsio/nats-server-config-reloader'
  - ruleName: 'prometheus-nats-exporter'
    baseRegistry: 'docker.io'
    baseImage: 'natsio/prometheus-nats-exporter'
    destinationRepo: 'imported/natsio/prometheus-nats-exporter'
  - ruleName: 'netbox'
    baseRegistry: 'docker.io'
    baseImage: 'netboxcommunity/netbox'
    destinationRepo: 'imported/netboxcommunity/netbox'
  - ruleName: 'nodejs'
    baseRegistry: 'docker.io'
    baseImage: 'library/node'
    destinationRepo: 'imported/library/node'
  - ruleName: 'nginx'
    baseRegistry: 'docker.io'
    baseImage: 'library/nginx'
    destinationRepo: 'imported/nginx'
  - ruleName: 'opentelemetry-collector'
    baseRegistry: 'docker.io'
    baseImage: 'otel/opentelemetry-collector-contrib'
    destinationRepo: 'imported/otel/opentelemetry-collector-contrib'
  - ruleName: 'node-exporter'
    baseRegistry: 'docker.io'
    baseImage: 'prom/node-exporter'
    destinationRepo: 'imported/prom/node-exporter'
  - ruleName: 'kube-slack'
    baseRegistry: 'docker.io'
    baseImage: 'willwill/kube-slack'
    destinationRepo: 'imported/willwill/kube-slack'
  - ruleName: 'jq-cache'
    baseRegistry: 'ghcr.io'
    baseImage: 'jqlang/jq'
    destinationRepo: 'imported/jqlang/jq'
  - ruleName: 'oathtool'
    baseRegistry: 'docker.io'
    baseImage: 'toolbelt/oathtool'
    destinationRepo: 'imported/toolbelt/oathtool'
  - ruleName: 'ryuk-cache'
    baseRegistry: 'docker.io'
    baseImage: 'testcontainers/ryuk'
    destinationRepo: 'imported/testcontainers/ryuk'
  - ruleName: 'alpine'
    baseRegistry: 'docker.io'
    baseImage: 'library/alpine'
    destinationRepo: 'imported/alpine'
  - ruleName: 'redis'
    baseRegistry: 'docker.io'
    baseImage: 'library/redis'
    destinationRepo: 'imported/redis'
  - ruleName: 'testcontainers-sshd'
    baseRegistry: 'docker.io'
    baseImage: 'testcontainers/sshd'
    destinationRepo: 'imported/testcontainers/sshd'
  - ruleName: 'williamyeh-java8'
    baseRegistry: 'docker.io'
    baseImage: 'williamyeh/java8'
    destinationRepo: 'imported/williamyeh/java8'
  - ruleName: 'azure-storage-azurite'
    baseRegistry: 'mcr.microsoft.com'
    baseImage: 'azure-storage/azurite'
    destinationRepo: 'imported/azure-storage/azurite'
  - ruleName: 'atmoz-sftp'
    baseRegistry: 'docker.io'
    baseImage: 'atmoz/sftp'
    destinationRepo: 'imported/atmoz/sftp'
  - ruleName: 'citizensadvice-clamav-mock'
    baseRegistry: 'docker.io'
    baseImage: 'citizensadvice/clamav-mock'
    destinationRepo: 'imported/citizensadvice/clamav-mock'
  - ruleName: 'library-ruby'
    baseRegistry: 'docker.io'
    baseImage: 'library/ruby'
    destinationRepo: 'imported/library/ruby'
  - ruleName: 'mikefarah-yq'
    baseRegistry: 'docker.io'
    baseImage: 'mikefarah/yq'
    destinationRepo: 'imported/mikefarah/yq'
  - ruleName: 'os-shell'
    baseRegistry: 'docker.io'
    baseImage: 'bitnami/os-shell'
    destinationRepo: 'imported/os-shell'
  - ruleName: 'wiremock'
    baseRegistry: 'docker.io'
    baseImage: 'wiremock/wiremock'
    destinationRepo: 'imported/wiremock/wiremock'

variables:
- name: acrName
  value: 'hmctspublic'
- name: targetRegistry
  value: 'hmctspublic.azurecr.io'
- name: keyvaultName
  value: 'infra-vault-prod'
- name: serviceConnection
  value: 'DCD-CNP-PROD'
- name: trivyVersion
  value: '0.68.1'
- name: severityThreshold
  value: 'CRITICAL,HIGH'
- name: trivyTimeout
  value: '10m'

stages:
# Stage 1: Import base images
- template: pipelines/base-image-import-stage.yml
  parameters:
    baseImagestoImport: ${{ parameters.baseImagestoImport }}
    serviceConnection: $(serviceConnection)
    keyvaultName: $(keyvaultName)
    acrName: $(acrName)
    trivyVersion: $(trivyVersion)
    severityThreshold: $(severityThreshold)
    trivyTimeout: $(trivyTimeout)

# Stage 2: Create and validate cache rules
- template: pipelines/cache-rules-stage.yml
  parameters:
    cacheRulesToValidate: ${{ parameters.cacheRulesToValidate }}
    serviceConnection: $(serviceConnection)
    keyvaultName: $(keyvaultName)
    acrName: $(acrName)
    trivyVersion: $(trivyVersion)
    severityThreshold: $(severityThreshold)
    trivyTimeout: $(trivyTimeout)
